# Generated by Django 5.0.6 on 2024-06-12 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Surah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('transliteration', models.CharField(max_length=255)),
                ('translation', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=50)),
                ('total_verses', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_verse', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('surah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.surah')),
            ],
        ),
        migrations.CreateModel(
            name='Verse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verse_id', models.IntegerField()),
                ('text', models.TextField()),
                ('translation', models.TextField()),
                ('surah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verses', to='api.surah')),
            ],
        ),
    ]
